
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#include "Text_common.h"
namespace SocialC2S
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_RequestLogon,
	};

	int g_RmiIDListCount = 1;
}
namespace SocialS2C
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ReplyLogon,
	};

	int g_RmiIDListCount = 1;
}
